Move mender-client-docker build to its own pipeline job
Split out mender-client-docker build from servers-build.sh, so that it
can be built independently of the rest of the micro-services.

On the one hand it just does not belong there any more, while on the
other hand this allows gitlab_trigger_client_publish for even lighter
pipelines.

Signed-off-by: Lluis Campos <lluis.campos@northern.tech>

diff --git a/gitlab-pipeline/stage/build.yml b/gitlab-pipeline/stage/build.yml
--- a/gitlab-pipeline/stage/build.yml
+++ b/gitlab-pipeline/stage/build.yml
@@ -31,6 +31,50 @@ build_client:
       - sysstat.log
       - sysstat.svg
 
+build_client_docker:
+  stage: build
+  only:
+    variables:
+      - $BUILD_CLIENT == "true"
+      - $RUN_INTEGRATION_TESTS == "true"
+  needs:
+    - init_workspace
+  image: docker:19.03
+  services:
+    - docker:dind
+  tags:
+    - docker
+  before_script:
+    # Default value, will later be overwritten if successful
+    - echo "failure" > /JOB_RESULT.txt
+    # Dependencies
+    - apk --update add python3 py-pip curl jq
+    - pip3 install pyyaml
+    # Post job status
+    - source ${CI_PROJECT_DIR}/build_revisions.env
+    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status pending "Gitlab ${CI_JOB_NAME} started" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"
+    # Prepare workspace
+    - export WORKSPACE=$(realpath ${CI_PROJECT_DIR}/..)
+    - mv workspace.tar.gz /tmp
+    - rm -rf ${WORKSPACE}
+    - mkdir -p ${WORKSPACE}
+    - cd ${WORKSPACE}
+    - tar -xf /tmp/workspace.tar.gz
+  script:
+    - docker_url=$($WORKSPACE/integration/extra/release_tool.py --map-name docker mender-client-docker docker_url)
+    - cd go/src/github.com/mendersoftware/mender
+    - ./tests/build-docker -t $docker_url:pr
+    - mkdir -p ${CI_PROJECT_DIR}/stage-artifacts
+    - docker save $docker_url:pr -o ${CI_PROJECT_DIR}/stage-artifacts/mender-client-docker.tar
+    - echo "success" > /JOB_RESULT.txt
+  after_script:
+    - ${CI_PROJECT_DIR}/scripts/github_pull_request_status $(cat /JOB_RESULT.txt) "Gitlab ${CI_JOB_NAME} finished" "${CI_JOB_URL}" "${CI_JOB_NAME}/${INTEGRATION_REV}"
+
+  artifacts:
+    expire_in: 2w
+    paths:
+      - stage-artifacts/
+
 build_servers:
   stage: build
   only:
@@ -69,7 +113,7 @@ build_servers:
 
     - mkdir -p stage-artifacts
     - for repo in `${CI_PROJECT_DIR}/../integration/extra/release_tool.py -l docker`; do
-        if ! echo $repo | grep -q mender-client-qemu; then
+        if ! echo $repo | grep -q mender-client; then
           docker_url=$(${CI_PROJECT_DIR}/../integration/extra/release_tool.py --map-name docker $repo docker_url);
           docker save $docker_url:pr -o stage-artifacts/${repo}.tar;
         fi;
@@ -82,7 +126,6 @@ build_servers:
     expire_in: 2w
     paths:
       - stage-artifacts/
-
 
 build_mender-cli:
   stage: build
